name: CI - Python

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "fix/**"
      - "release/**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create venv
        run: |
          python -m venv .venv

      - name: Install dependencies
        run: |
          . .venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint (flake8)
        run: |
          . .venv/bin/activate
          if [ -f requirements-dev.txt ]; then
            flake8 .
          else
            echo "requirements-dev.txt not found -> skip lint"
          fi

      - name: Test (pytest)
        run: |
          . .venv/bin/activate
          if [ -f requirements-dev.txt ]; then
            pytest
          else
            echo "requirements-dev.txt not found -> skip tests"
          fi
