name: Deploy - Docker on Chronos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    env:
      # 各アプリごとに必ず書き換える（テンプレ置換ポイント）
      APP_DIR: /home/chronos/apps/YOUR_APP_NAME

    steps:
      - name: Checkout (to workspace)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Sync repository to deploy directory
        run: |
          set -euo pipefail
          mkdir -p "${APP_DIR}"

          if command -v rsync >/dev/null 2>&1; then
            rsync -a --delete \
              --exclude ".git" \
              --exclude ".github" \
              "./" "${APP_DIR}/"
          else
            # rsync が無い場合のフォールバック（deleteはしない）
            cp -a ./ "${APP_DIR}/"
          fi

      - name: Deploy (docker compose up)
        run: |
          set -euo pipefail
          cd "${APP_DIR}"

          if [ -f docker-compose.yml ] || [ -f docker-compose.yaml ]; then
            docker compose pull || true
            docker compose up -d --build
          else
            echo "docker-compose.yml(.yaml) not found in ${APP_DIR}"
            exit 1
          fi
